// Shared by the browser and the /api/shares routes.

/** Public ids are nanoid(12), generated by the server. */
const SHARE_ID_LENGTH = 12
const SHARE_ID = /^[\w-]{12}$/

const MAX_SLUG_LENGTH = 60

/** Owner tokens are 32 random bytes in base64url (see token.ts). */
export const TOKEN_PATTERN = /^[\w-]{43}$/

/** Largest document that can be published (bytes of UTF-8). */
export const MAX_SHARE_BYTES = 1024 * 1024

export const MAX_TITLE_LENGTH = 200

export const isShareId = (id: string) => SHARE_ID.test(id)

/** A title as it reads in a link: ASCII letters and digits joined by hyphens. Empty when none are left. */
export function titleSlug(title: string): string {
  return title
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, MAX_SLUG_LENGTH)
    .replace(/^-+|-+$/g, "")
}

/**
 * Path of a shared document: `/s/<title-slug>-<id>`. Only the id identifies the document;
 * the slug makes the link readable and simply follows the current title.
 */
export function sharePath(id: string, title: string): string {
  const slug = titleSlug(title)
  return `/s/${slug ? `${slug}-` : ""}${id}`
}

/** The share id that ends a /s/ path segment, with or without a slug in front, or null. */
export function shareIdFromSegment(segment: string): string | null {
  const id = segment.slice(-SHARE_ID_LENGTH)
  if (!isShareId(id)) return null
  // a bare id (links from before slugs), or a slug and a hyphen before it
  return segment.length === SHARE_ID_LENGTH || segment.at(-SHARE_ID_LENGTH - 1) === "-" ? id : null
}

/** Size of `text` in UTF-8, which is what the limit counts. */
export const utf8Length = (text: string) => new TextEncoder().encode(text).byteLength
