// Shared by the browser and the /api/shares routes.

/** Public ids are nanoid(12), generated by the server. */
const SHARE_ID = /^[\w-]{12}$/

/** Owner tokens are 32 random bytes in base64url (see token.ts). */
export const TOKEN_PATTERN = /^[\w-]{43}$/

/** Largest document that can be published (bytes of UTF-8). */
export const MAX_SHARE_BYTES = 1024 * 1024

export const MAX_TITLE_LENGTH = 200

export const isShareId = (id: string) => SHARE_ID.test(id)

/** Size of `text` in UTF-8, which is what the limit counts. */
export const utf8Length = (text: string) => new TextEncoder().encode(text).byteLength
